### PR TITLE
pass token in query params

### PR DESCRIPTION
**Pull request by patrickarlt**
Browser tests fail.  I suspect something is wrong with setup or something but I can't figure it out. It does work in browser though with a few simple debug tests.

### CODE REVIEW

**Comment by kneemer** [comment]
Before merging and bumping the version could you fix misspelling of `could` on https://github.com/Esri/geotrigger-js/blob/master/geotrigger.js#L251 and https://github.com/Esri/geotrigger-js/blob/master/geotrigger.js#L285?

**Comment by ngoldman** [comment]
@patrickarlt I merged @kneemer's PR, this one's probably good to go.

**Comment by ngoldman** [comment]
@patrickarlt would be good to set up `.travis.yml` on this, did we ever try that?

**Comment by jgravois** [comment]
@kneemer set up to travis to skip running tests on forked PRs (because encrypted variables aren't supported).

will revert if need be :see_no_evil:

**Pull request merged**
